app:
  eureka-hostname: localhost
  eureka-port: 8761
  server-port: 8181
  application-name: api-gateway

spring:
  application:
    name: ${app.application-name}
  profiles:
    active:
      - local
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/api/product/**
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/api/order/**
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
          - Path=/api/inventory/**
      - id: notification-service
        uri: lb://notification-service
        predicates:
          - Path=/api/notification/**
      - id: discovery-server
        uri: http://${app.eureka-hostname}:${app.eureka-port}
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/
      - id: discovery-server-static
        uri: http://${app.eureka-hostname}:${app.eureka-port}
        predicates:
          - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: ${app.server-port}
